site_name: pytest-pumpkin-spice
site_description: A pytest plugin that makes your test reporting pumpkin-spiced
site_author: Josh Grant

theme: readthedocs

repo_url: https://github.com/hackebrot/pytest-pumpkin-spice

pages:
- Home: index.md
